name: Pre-merge checks
on:
  - pull_request

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 25
      - uses: actions/checkout@v4
      - run: ./gradlew spotlessCheck
